### ISSUE TITLE
com/norconex/commons/lang/map/Properties documentation improvement

### ISSUE THREAD

**Issue by liar666** [Norconex/commons-lang#1]
Hi again,

I was just wandering what would com/norconex/commons/lang/map/Properties.getBoolean(null) would return.
I could not find it in the docs:
https://www.norconex.com/product/commons-lang/apidocs/com/norconex/commons/lang/map/Properties.html#getBoolean-java.lang.String-
But I found the code here and ran it:
https://github.com/Norconex/commons-lang/blob/master/norconex-commons-lang/src/main/java/com/norconex/commons/lang/map/Properties.java

I discovered it returns false :)

Would be great if it would be written in the doc :)

**Comment by essiembre** [comment]
That's not entirely accurate.  `getBoolean(null)` will return whatever you have assigned for the `null` key (if anything).  `false` is always returned when there are no values found.

For instance, the following will return `true`:

``` java
Properties p = new Properties();
p.addBoolean(null, true);
System.out.println("What is it? " + p.getBoolean(null));
```

In any case, I have improved the Javadoc for that method.  Re-open if it is still unclear to you.  Thanks for the suggestion!
