### ISSUE TITLE
Feature Request - support java 8 java.time.TemporalAccessor types

### ISSUE THREAD

**Issue by danizen** [Norconex/commons-lang#10]
### CURRENT BEHAVIOR

map.Properties supports java.util.Date, but Java 8 mostly deprecates it.

### DESIRED BEHAVIOR 

concrete implementations of java.time.TemporalAccessor, such as LocalTime, YearMonth, Year, etc. should be supported through a DateTimeFormatter that is sufficiently broad.

### MOTIVATION

Feature requested of me is that my code find the "most recent date" from a page's content in the most concrete way.    The page https://ghr.nlm.nih.gov/condition/ppm-x-syndrome is a good example, where we have the choice to support a "Reviewed Date" and a "Published Date", but these have different resolution.

I've built a very flexible tagger that can take a date pattern (regex) and a date format (for java.time.format.DateTImeFormatter), and even a type, such as java.time.YearMonth, and then scan the content or a sourceField.   The configured scanners can also have a priority.   So, very pluggable...

### WORK AROUND

I convert to LocalDate and then toString gives it format "2018-01-01" as I call setString.   This is OK for now.

### PRIORITY

Low, but I wanted to capture the issue along with its context.

**Comment by essiembre** [comment]
Done in version 2.x.  Supported types:

* Date
* LocalDateTime
* ZonedDateTime
* Instant

As of this writing, the Date and LocalDateTime have their own getter methods.  For the other two, you would use this more generic approach: 

```java
ZonedDateTime zdt = properties.get("myKey", ZonedDateTime.class);
```
