### ISSUE TITLE
URLNormalizer.sortQueryParameters() incorrect when fragment exists

### ISSUE THREAD

**Issue by neilmcguigan** [Norconex/commons-lang#2]
String url = new URLNormalizer("http://example.com?z=1&a=1#yolo").sortQueryParameters().toString();

assertEquals("http://example.com?a=1&z=1#yolo", url); //fails

**Comment by essiembre** [comment]
A new [release](https://www.norconex.com/product/commons-lang/download.html) was just made this fix.  Please give it a try.
