### ISSUE TITLE
EncryptionKey is insecure because no iv is used

### ISSUE THREAD

**Issue by danizen** [Norconex/commons-lang#5]
I used the `EncryptionUtil` twice in a row to encrypt the same input, once with the key being the actual key, and again as the key being a file I will place in my repository.   I noticed that I got the same base64 encoded value.

This is a common misuse of Symmetric encryption - you are supposed to produce a random iv/nonce that is used to salt the encryption.   The encrypted binary value you produce then is composed of the nonce concatenated with the encrypted value.   Then, the binary value is encoded in base64, stored in a file, whatever.

When decrypting, you break-up the encrypted binary into the iv/nonce and the crypttext.

@essiembre, don't let Bruce Schneier know but give some thought to fixing it.   My suggestion is that when you are decrypting binary data that is too short to contain the nonce/iv, you decrypt it (silently), and when you encrypt in future, always include a nonce/iv.

**Comment by danizen** [comment]
@essiembre, this isn't urgent - I think I can code this up it this weekend.   It isn't at all like adding referenceFrom meta-data, it is much less embedded in everything, and so I'll take it on and give something back.

**Comment by essiembre** [comment]
Perfect! I shall await the pull-request then. :-)   Use the "develop" branch, please.

**Comment by danizen** [comment]
@essiembre , I am now moving to production, and so I have to get this done.  After I started coding up a fix, and had a concern about backwards compatibility.   Because the algorithm you currently use has no HMAC, it is difficult to detect whether a new algorithm should be used - the old algorithm will be used if a magic number is not seen at the beginning of the encrypted text - is this OK with you?

**Comment by danizen** [comment]
My security team wants to push this to places that will inconvenience you.   JCE standard which is available in the Oracle and OpenJDK supports AES 128bit, but they want me to use both AES 256 and Java keytool (a new EncryptionKey.Source).   

I am making that a different bug and just supporting an Hmac and AES 128 bit encryption over DES and SHA256 over MD5.

**Comment by danizen** [comment]
Pull request ready - I am going to test with OpenJDK 7 and 8 at home, and report back here.   I don't want any surprises for your downstream clients.

**Comment by danizen** [comment]
I tested with OpenJDK 8 - its fine.   I tested with OpenJDK 7, and got an error.  Since the compiler is targeting Java version 1.7, I assume its not OK, and I'll go back to the drawing board on this encryption code.

I've also read recently [RFC-2898](https://tools.ietf.org/html/rfc2898) and a [blog article](https://cryptosense.com/parameter-choice-for-pbkdf2/) that convince me that increasing the number of iterations is needed, but also suggest that putting a MAC in the encrypted message bytes is good so that we know cleanly when the encrypted password isn't right.

**Comment by danizen** [comment]
I've fixed this, and it should be ready to merge.

**Comment by essiembre** [comment]
Merged.  Please confirm the new [1.15.0-SNAPSHOT](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/norconex/commons/norconex-commons-lang/1.15.0-SNAPSHOT/norconex-commons-lang-1.15.0-20180311.200306-1.jar) works for you.

**Comment by essiembre** [comment]
[1.15.0 released](https://www.norconex.com/product/commons-lang/)

**Comment by danizen** [comment]
@essiembre , I had a chance to update my code to 1.15.0, and it works great.
Thanks.
