### ISSUE TITLE
Support U.S. Federal government 256 byte key length requirement

### ISSUE THREAD

**Issue by danizen** [Norconex/commons-lang#8]
*Current Behavior*

* The size of the key used by `EncryptionKey` is not tunable.

*Desired Behavior*

* Add a new `EncryptionKey` attribute `passwordKeySize` that is a size in bytes.   It will default to 128.
* Enhance `EncryptionKeyUtil` to read the key size from the `EncryptionKey`.   If a user specifies a `passwordKeySize that doesn't work on their Java installation, they get the exception. 
* Enhance `com.norconex.commons.lang.config.PasswordKeyUtil` so that it will parse a `passwordKeySize` XML element with an integer value.
* Update downstream code that parses/formats `passwordKey` and `passwordKeySource` XML elements to use the `PasswordKeyUtil`.

**Comment by danizen** [comment]
@essiembre, I think I can work on this too, but I'm taking it one step at a time.   I have first to make sure the current algorithm works.

**Comment by danizen** [comment]
I've fixed this and it should be ready to merge.

**Comment by essiembre** [comment]
Merged.  Please confirm the new [1.15.0-SNAPSHOT](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/norconex/commons/norconex-commons-lang/1.15.0-SNAPSHOT/norconex-commons-lang-1.15.0-20180311.200306-1.jar) works for you.

**Comment by danizen** [comment]
Will do.

**Comment by essiembre** [comment]
[1.15.0 released](https://www.norconex.com/product/commons-lang/)
