### ISSUE TITLE
Support a KeyStore implementation

### ISSUE THREAD

**Issue by danizen** [Norconex/commons-lang#9]
*Current Behavior*

None of the EncryptionKey.Source implementations are actually a KeyStore.

*Desired Behavior*

* Add a new EncryptionKey.Source that is a keystore.  The passwordKey here must be the "alias" for a key stored in the keystore.
* Add static functions to EncryptionKeyUtil to "register" the keystore, which has persumably already been loaded and unlocked.
* Add configuration elements to downstream projects such as collector core to allow the KeyStore path and its key to be specified somehow.

*Snarky Comment*

My security people want this, but it is really icing on the cake.

**Comment by danizen** [comment]
This will have to wait a bit, but if I can fix it later, I will.

**Comment by danizen** [comment]
I'm no longer a fan.   Keystore is no more secure than what norconex has already.

**Comment by essiembre** [comment]
No problem, thanks for following up.
